/**
 * .gitignore Wizard — 内置模板数据
 *
 * 数据来源: https://github.com/github/gitignore
 * 包含最常用的 30+ 种模板。
 */

const TEMPLATE_DATA = [
  // ===== 后端语言 =====
  {
    id: "python",
    name: "Python",
    category: "backend",
    content: `# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]
*$py.class

# C extensions
*.so

# Distribution / packaging
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
share/python-wheels/
*.egg-info/
.installed.cfg
*.egg
MANIFEST

# PyInstaller
*.manifest
*.spec

# Installer logs
pip-log.txt
pip-delete-this-directory.txt

# Unit test / coverage reports
htmlcov/
.tox/
.nox/
.coverage
.coverage.*
.cache
nosetests.xml
coverage.xml
*.cover
*.py,cover
.hypothesis/
.pytest_cache/
cover/

# Translations
*.mo
*.pot

# Django stuff
*.log
local_settings.py
db.sqlite3
db.sqlite3-journal

# Flask stuff
instance/
.webassets-cache

# Scrapy stuff
.scrapy

# Sphinx documentation
docs/_build/

# PyBuilder
.pybuilder/
target/

# Jupyter Notebook
.ipynb_checkpoints

# IPython
profile_default/
ipython_config.py

# pyenv
.python-version

# pipenv
Pipfile.lock

# poetry
poetry.lock

# pdm
.pdm.toml

# PEP 582
__pypackages__/

# Celery stuff
celerybeat-schedule
celerybeat-schedule.db

# SageMath parsed files
*.sage.py

# Environments
.env
.env.local
.venv
env/
venv/
ENV/
env.bak/
venv.bak/

# Spyder project settings
.spyderproject
.spyproject

# Rope project settings
.ropeproject

# mkdocs documentation
/site

# mypy
.mypy_cache/
.dmypy.json
dmypy.json

# Pyre type checker
.pyre/

# pyright
.pyright/

# VSCode
.vscode/`,
  },
  {
    id: "node",
    name: "Node.js",
    category: "backend",
    content: `# Dependency directories
node_modules/
jspm_packages/

# npm
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# yarn
.yarn/
.yarnrc.yml
.yarn/install-state.gz

# pnpm
pnpm-lock.yaml
.pnpm-store/

# TypeScript output
dist/
build/
out/
*.tsbuildinfo

# Environment variables
.env
.env.local
.env.*.local

# IDE
.idea/
.vscode/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Logs
*.log
logs/

# Coverage
coverage/
.nyc_output/

# Runtime
pids/
*.pid
*.seed

# Grunt
.grunt/

# Bower
bower_components/

# Serverless
.serverless/

# Next.js
.next/

# Nuxt
.nuxt/

# Vue
dist/

# Turborepo
.turbo/`,
  },
  {
    id: "go",
    name: "Go",
    category: "backend",
    content: `# Binaries for programs and plugins
*.exe
*.exe~
*.dll
*.so
*.dylib

# Test binary, built with \`go test -c\`
*.test

# Output of the go coverage tool, specifically when used with LiteIDE
*.out

# Dependency directories (replace the module directory)
vendor/

# Go workspace file
go.work

# IDE
.idea/
.vscode/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Env
.env`,
  },
  {
    id: "rust",
    name: "Rust",
    category: "backend",
    content: `# Generated by Cargo
/target/

# Remove Cargo.lock from gitignore if creating an end-user application
Cargo.lock

# These are backup files generated by rustfmt
**/*.rs.bk

# MSVC Windows builds of rustc generate these
*.pdb

# IDE
.idea/
.vscode/
*.swp

# OS
.DS_Store
Thumbs.db`,
  },
  {
    id: "java",
    name: "Java",
    category: "backend",
    content: `# Compiled class file
*.class

# Log file
*.log

# BlueJ files
*.ctxt

# Mobile Tools for Java (J2ME)
.mtj.tmp/

# Package Files
*.jar
*.war
*.nar
*.ear
*.zip
*.tar.gz
*.rar

# virtual machine crash logs
hs_err_pid*
replay_pid*

# Maven
target/
pom.xml.tag
pom.xml.releaseBackup
pom.xml.versionsBackup
pom.xml.next
release.properties
dependency-reduced-pom.xml
buildNumber.properties
.mvn/timing.properties
.mvn/wrapper/maven-wrapper.jar

# Gradle
.gradle/
build/
!gradle/wrapper/gradle-wrapper.jar

# IntelliJ IDEA
.idea/
*.iws
*.iml
*.ipr
out/

# Eclipse
.settings/
.project
.classpath
*.prefs

# NetBeans
nbproject/private/
build/
nbbuild/
nbdist/
.nb-gradle/

# VS Code
.vscode/

# OS
.DS_Store
Thumbs.db`,
  },
  {
    id: "ruby",
    name: "Ruby",
    category: "backend",
    content: `*.rbc
*.gem
*.sassc
*.lock
.sass-cache/
.bundler/
.bundle/
vendor/bundle
vendor/ruby

# Compiled
*.o
*.obj
*.class

# RDoc
rdoc/

# Rails
log/*
tmp/*
public/assets
public/packs
public/system
storage/
config/master.key
config/credentials.yml.enc
db/schema.rb

# Rails - Active Storage
storage/

# Spring
.spring/

# Byebug
.byebug_history

# RSpec
spec/examples.txt
spec/tmp

# Minitest
test/tmp

# Capybara
tmp/capybara

# OS
.DS_Store
Thumbs.db

# Env
.env
.env.local`,
  },
  {
    id: "php",
    name: "PHP",
    category: "backend",
    content: `vendor/
composer.lock
composer.phar

# PHPUnit
.phpunit.result.cache
.phpunit.cache

# Laravel
.env
.env.*.local
storage/*.key
bootstrap/cache/**

# Symfony
/.env
/var/
/cache/
vendor/

# CodeIgniter
application/cache/

# IDE
.idea/
.vscode/
*.swp

# OS
.DS_Store
Thumbs.db`,
  },
  {
    id: "csharp",
    name: "C# / .NET",
    category: "backend",
    content: `## .NET
**/[Bb]in/
**/[Oo]bj/
**/[Dd]ebug/
**/[Rr]elease/
*.user
*.suo
*.sln.docstates
*.userprefs

# NuGet
**/[Pp]ackages/*
!**/[Pp]ackages/build/
*.nupkg
**/[Pp]ackages/repositories.config

# Visual Studio
.vs/
*.sln.ide/

# Rider
.idea/
*.sln.iml

# OS
.DS_Store
Thumbs.db`,
  },

  // ===== 前端框架 =====
  {
    id: "react",
    name: "React (CRA)",
    category: "frontend",
    content: `# Dependencies
node_modules/

# Build
build/

# Testing
coverage/

# Environment
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

# IDE
.idea/
.vscode/
*.swp

# OS
.DS_Store
Thumbs.db

# Logs
*.log

# Misc
*.tsbuildinfo
npm-debug.log*
yarn-debug.log*
yarn-error.log*`,
  },
  {
    id: "vue",
    name: "Vue.js",
    category: "frontend",
    content: `# Dependencies
node_modules/

# Build
dist/

# Local env
.env
.env.local
.env.*.local

# Logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Editor
.vscode/*
!.vscode/extensions.json
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Testing
coverage/

# TypeScript
*.tsbuildinfo

# Vite
.vite/`,
  },
  {
    id: "angular",
    name: "Angular",
    category: "frontend",
    content: `# Dependencies
node_modules/

# Build
dist/

# Angular specific
*.js.map
*.js
!src/**/*.js

# Testing
coverage/

# IDE
.idea/
.vscode/
*.swp

# OS
.DS_Store
Thumbs.db

# Env
.env
.env.local`,
  },
  {
    id: "nextjs",
    name: "Next.js",
    category: "frontend",
    content: `# Dependencies
node_modules/

# Build
.next/
out/

# Environment
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

# Logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# TypeScript
*.tsbuildinfo

# IDE
.vscode/
.idea/
*.swp

# OS
.DS_Store
Thumbs.db

# Testing
coverage/

# Next.js
.next/
*.tsbuildinfo`,
  },

  // ===== 移动端 =====
  {
    id: "android",
    name: "Android",
    category: "mobile",
    content: `# Built application files
*.apk
*.ap_
*.aab

# Files for the ART/Dalvik VM
*.dex

# Java class files
*.class

# Generated files
bin/
gen/
out/

# Gradle files
.gradle/
build/

# Local configuration file
local.properties

# Android Studio
*.iml
.idea/
.navigation/
captures/
.externalNativeBuild/
.cxx/

# OS
.DS_Store
Thumbs.db`,
  },
  {
    id: "ios",
    name: "iOS / Xcode",
    category: "mobile",
    content: `# Xcode
*.pbxuser
!default.pbxuser
*.mode1v3
!default.mode1v3
*.mode2v3
!default.mode2v3
*.perspectivev3
!default.perspectivev3
xcuserdata/
*.xccheckout
*.moved-aside
DerivedData/
*.hmap
*.ipa
*.xcuserstate

# CocoaPods
Pods/
!Podfile.lock

# Carthage
Carthage/Build/

# Swift Package Manager
.build/
.swiftpm/

# Accio
Accio/

# OS
.DS_Store

# Env
.env`,
  },
  {
    id: "flutter",
    name: "Flutter / Dart",
    category: "mobile",
    content: `# Flutter
.flutter-plugins
.flutter-plugins-dependencies
.idea/
.dart_tool/
.packages
build/
*.iml

# Dart
.dart_tool/
.packages
.pub-cache/
.pub/
build/
*.js_
*.js.deps
*.js.map

# Android
android/.gradle/
android/app/build/
android/local.properties

# iOS
ios/Pods/
ios/.symlinks/

# IDE
.vscode/
*.swp

# OS
.DS_Store
Thumbs.db`,
  },

  // ===== DevOps & 工具 =====
  {
    id: "docker",
    name: "Docker",
    category: "devops",
    content: `# Docker
.docker/
docker-compose.override.yml

# Build
Dockerfile.*.build
*.tar
*.tar.gz

# Env
.env
.env.local

# Logs
*.log

# OS
.DS_Store
Thumbs.db`,
  },
  {
    id: "terraform",
    name: "Terraform",
    category: "devops",
    content: `# Local .terraform directories
**/.terraform/

# .tfstate files
*.tfstate
*.tfstate.*

# Crash log files
crash.log
crash.*.log

# Exclude all .tfvars files, which are likely to contain sensitive data
*.tfvars
*.tfvars.json

# Ignore override files
override.tf
override.tf.json
*_override.tf
*_override.tf.json

# Ignore CLI configuration files
.terraformrc
terraform.rc

# OS
.DS_Store
Thumbs.db`,
  },
  {
    id: "ansible",
    name: "Ansible",
    category: "devops",
    content: `# Inventory
*.retry

# Vault
*.vault

# OS
.DS_Store
Thumbs.db

# Logs
*.log`,
  },
  {
    id: "kubernetes",
    name: "Kubernetes",
    category: "devops",
    content: `# Secrets (should be managed via SealedSecrets / External Secrets)
**/secrets*.yaml
**/secret*.yaml
!**/sealed-secret*.yaml

# Local kubeconfig
.kube/config
.kube/

# Helm
charts/**/charts/*.tgz

# OS
.DS_Store
Thumbs.db`,
  },
  {
    id: "github-actions",
    name: "GitHub Actions",
    category: "devops",
    content: `# GitHub Actions cache
.github/actions/**/node_modules/

# Secrets
.env
.env.*

# OS
.DS_Store
Thumbs.db`,
  },

  // ===== 语言 & 平台 =====
  {
    id: "cpp",
    name: "C / C++",
    category: "lang",
    content: `# Compiled Object files
*.slo
*.lo
*.o
*.obj

# Precompiled Headers
*.gch
*.pch

# Compiled Dynamic libraries
*.so
*.dylib
*.dll

# Fortran module files
*.mod
*.smod

# Compiled Static libraries
*.lai
*.la
*.a
*.lib

# Executables
*.exe
*.out
*.app

# Build directories
/build/
/cmake-build-*/
/out/

# IDE
.idea/
.vscode/
*.swp

# OS
.DS_Store
Thumbs.db`,
  },
  {
    id: "swift",
    name: "Swift",
    category: "lang",
    content: `# Xcode
*.pbxuser
*.mode1v3
*.mode2v3
*.perspectivev3
xcuserdata
*.xccheckout
*.moved-aside
DerivedData
*.hmap
*.ipa
*.xcuserstate
**/.xcode.env.local

# Swift Package Manager
.build/
.swiftpm/

# CocoaPods
Pods/

# OS
.DS_Store`,
  },
  {
    id: "kotlin",
    name: "Kotlin",
    category: "lang",
    content: `# Compiled class file
*.class

# Log file
*.log

# BlueJ files
*.ctxt

# Package Files
*.jar
*.war
*.nar
*.ear
*.zip
*.tar.gz
*.rar

# Kotlin
*.kotlin_module

# Gradle
.gradle/
build/

# IntelliJ IDEA
.idea/
*.iml
*.iws
out/

# OS
.DS_Store
Thumbs.db`,
  },
  {
    id: "scala",
    name: "Scala",
    category: "lang",
    content: `# Scala
*.class
*.log

# SBT
target/
lib_managed/
src_managed/
project/project/
project/target/

# IntelliJ
.idea/
*.iml
*.iws

# Bloop
.bloop/

# Metals
.metals/

# VS Code
.vscode/

# OS
.DS_Store
Thumbs.db`,
  },
  {
    id: "elixir",
    name: "Elixir",
    category: "lang",
    content: `# Elixir
_build/
deps/
*.ez

# Phoenix
priv/static/

# Dialyxir
dialyzer.plt
dialyzer.plt.hash

# IDE
.idea/
.vscode/
*.swp

# OS
.DS_Store
Thumbs.db`,
  },
  {
    id: "haskell",
    name: "Haskell",
    category: "lang",
    content: `# Haskell
dist/
dist-newstyle/
.cabal-sandbox/
cabal.sandbox.config
*.cabal.lock
.stack-work/
.hlint.yaml

# IDE
.idea/
.vscode/
*.swp

# OS
.DS_Store
Thumbs.db`,
  },

  // ===== 数据 & 科学 =====
  {
    id: "jupyter",
    name: "Jupyter Notebook",
    category: "data",
    content: `# Jupyter
.ipynb_checkpoints/

# Cell outputs should be cleared before committing
.ipynb_snapshot/

# OS
.DS_Store
Thumbs.db

# Data
*.csv
*.json
*.pickle
*.pkl
data/
*.h5`,
  },
  {
    id: "r",
    name: "R",
    category: "data",
    content: `# R
.RData
.Rhistory
.Renviron
.Renviron.example
.Rprofile
*.Rproj
.Rproj.user

# RStudio
.Ruserdata

# OS
.DS_Store
Thumbs.db

# Data
*.csv
*.tsv`,
  },
  {
    id: "matlab",
    name: "MATLAB",
    category: "data",
    content: `# MATLAB
*.asv
*.m~
*.mat

# Simulink
*.slxc

# OS
.DS_Store
Thumbs.db`,
  },
  {
    id: "unity",
    name: "Unity",
    category: "data",
    content: `# Unity
[Ll]ibrary/
[Tt]emp/
[Oo]bj/
[Bb]uild/
[Bb]uilds/
[Ll]ogs/
[Uu]ser[Ss]ettings/
*.csproj
*.sln
*.user
*.unityproj
*.pidb
*.booproj

# Visual Studio
.vs/
*.sln.ide/

# JetBrains Rider
.idea/

# OS
.DS_Store
Thumbs.db`,
  },

  // ===== 通用 =====
  {
    id: "macos",
    name: "macOS",
    category: "通用",
    content: `# General
.DS_Store
.DS_Store?
.AppleDouble
.LSOverride

# Icon must end with two \\r
Icon

# Thumbnails
._*

# Files that might appear in the root of a volume
.DocumentRevisions-V100
.fseventsd
.Spotlight-V100
.TemporaryItems
.Trashes
.VolumeIcon.icns
.com.apple.timemachine.donotpresent

# Directories potentially created on remote AFP share
.AppleDB
.AppleDesktop
Network Trash Folder
Temporary Items
.apdisk`,
  },
  {
    id: "windows",
    name: "Windows",
    category: "通用",
    content: `# Windows thumbnail cache
Thumbs.db
Thumbs.db:encryptable
ehthumbs.db
ehthumbs_vista.db

# Dump file
*.stackdump

# Folder config file
[Dd]esktop.ini

# Recycle Bin used on file shares
$RECYCLE.BIN/

# Windows Installer files
*.cab
*.msi
*.msix
*.msm
*.msp

# Windows shortcuts
*.lnk`,
  },
  {
    id: "vscode",
    name: "VS Code (User)",
    category: "通用",
    content: `# VS Code
.vscode/*
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json
!.vscode/*.code-snippets

# Local History for VS Code
.vscode/.history/

# Built-in extension local storage
.vscode/.browse-live.*`,
  },
  {
    id: "latex",
    name: "LaTeX",
    category: "通用",
    content: `# LaTeX
*.aux
*.bbl
*.blg
*.brf
*.dvi
*.fdb_latexmk
*.fls
*.lof
*.log
*.lot
*.nav
*.out
*.ps
*.rdp
*.snm
*.synctex.gz
*.toc
*.vrb
*.xdv

# OS
.DS_Store
Thumbs.db`,
  },
];

// 分类映射
const CATEGORIES = [
  { id: "all", name: "全部" },
  { id: "backend", name: "后端语言" },
  { id: "frontend", name: "前端框架" },
  { id: "mobile", name: "移动端" },
  { id: "devops", name: "DevOps" },
  { id: "lang", name: "编程语言" },
  { id: "data", name: "数据 & 科学" },
  { id: "通用", name: "通用" },
];

// 额外忽略项（内置片段）
const EXTRA_PATTERNS = {
  optEnv: {
    content: `# Environment variables
.env
.env.local
.env.*.local`,
    explanation: "环境变量文件，可能包含密钥和 API Token，永远不应该提交到版本控制",
  },
  optDSStore: {
    content: `# macOS
.DS_Store`,
    explanation: "macOS 文件夹元数据缓存文件，每个访达打开的目录都会生成",
  },
  optThumbsdb: {
    content: `# Windows
Thumbs.db`,
    explanation: "Windows 图片缩略图缓存数据库",
  },
  optVscode: {
    content: `# VS Code (project)
.vscode/`,
    explanation: "编辑器配置目录——除非团队统一标准，否则建议忽略，避免覆盖每个人的个人设置",
  },
  optIdea: {
    content: `# JetBrains IDEs
.idea/
*.iml`,
    explanation: "IntelliJ IDEA / WebStorm / PyCharm 等 JetBrains IDE 项目配置目录",
  },
  optLogs: {
    content: `# Logs
*.log
logs/`,
    explanation: "运行时生成的日志文件，不同环境内容不同，不应进入版本控制",
  },
};
